# Tensor Flow

In [148]:
import tensorflow as tf

## A. Membuat sebuah tensor dengan shape(5,5) dengan nilai random

In [149]:
# membuat variable random_tensor
random_tensor = tf.random.normal([5,5], seed = 1)

# mengecek nilai constant
random_tensor.numpy()

array([[-0.10106637,  0.46920854, -1.0703483 ,  0.86057067, -0.79130745],
       [ 0.09045956,  0.94828707,  0.47215232,  2.038057  , -0.45528835],
       [-0.47464088, -0.0629163 ,  0.397867  ,  0.22886398, -0.03072531],
       [-0.28157505,  0.7958308 ,  0.71336466, -0.28134418,  0.9798792 ],
       [ 1.0570775 , -0.4569331 , -0.3012637 ,  1.034456  , -1.0373529 ]],
      dtype=float32)

## B. Membuat tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima

In [150]:
# membuat variable prime_tensor
prime_tensor = tf.constant([[2, 3, 5, 7, 11], [13, 17, 19, 23, 29], [31, 37, 41, 43, 47], [53, 59, 61, 71, 73], [79, 83, 89, 97, 101]], shape=[5,5], dtype=tf.float32)

# mengecek nilai constant
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

## C. Menampilkan dimensi dari kedua variable diatas

In [151]:
# Dimensi variable random_shape
print(random_tensor.shape)
print(random_tensor.get_shape())
print(tf.shape(random_tensor))

print()

# Dimensi variable prime_tensor
print(prime_tensor.shape)
print(prime_tensor.get_shape())
print(tf.shape(prime_tensor))

(5, 5)
(5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32)

(5, 5)
(5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32)


## D. Menampilkan hasil perhitungan aritmetika kedua variable (5 operasi)

In [152]:
# Memindahkan variable ke variable yang lebih mudah dalam pemanggilannya
a = random_tensor
b = prime_tensor

### Penjumlahan

In [153]:
print(tf.add(a, b))

tf.Tensor(
[[ 1.8989336  3.4692085  3.9296517  7.860571  10.208693 ]
 [13.09046   17.948288  19.472153  25.038057  28.544712 ]
 [30.525358  36.937084  41.397865  43.228863  46.969276 ]
 [52.718426  59.79583   61.713364  70.71866   73.97988  ]
 [80.057076  82.54307   88.69874   98.034454  99.96265  ]], shape=(5, 5), dtype=float32)


### Pengurangan


In [154]:
print(tf.subtract(a, b))

tf.Tensor(
[[  -2.1010664   -2.5307915   -6.0703483   -6.139429   -11.791307 ]
 [ -12.90954    -16.051712   -18.527847   -20.961943   -29.455288 ]
 [ -31.474642   -37.062916   -40.602135   -42.771137   -47.030724 ]
 [ -53.281574   -58.20417    -60.286636   -71.28134    -72.02012  ]
 [ -77.942924   -83.45693    -89.30126    -95.965546  -102.03735  ]], shape=(5, 5), dtype=float32)


### Pembagian

In [155]:
print(tf.divide(a, b))

tf.Tensor(
[[-0.05053319  0.15640284 -0.21406965  0.12293867 -0.07193704]
 [ 0.00695843  0.05578159  0.02485012  0.08861118 -0.0156996 ]
 [-0.015311   -0.00170044  0.00970407  0.00532242 -0.00065373]
 [-0.00531274  0.01348866  0.0116945  -0.00396259  0.013423  ]
 [ 0.01338073 -0.00550522 -0.00338499  0.01066449 -0.01027082]], shape=(5, 5), dtype=float32)


### Perkalian

In [156]:
print(tf.multiply(a, b))

tf.Tensor(
[[  -0.20213275    1.4076257    -5.3517413     6.0239944    -8.704382  ]
 [   1.1759742    16.12088       8.970894     46.875313    -13.203362  ]
 [ -14.713867     -2.327903     16.312548      9.841151     -1.4440894 ]
 [ -14.923478     46.954018     43.515244    -19.975437     71.53118   ]
 [  83.509125    -37.92545     -26.812468    100.34223    -104.772644  ]], shape=(5, 5), dtype=float32)


### pangkat

In [157]:
print(tf.pow(a, b))

tf.Tensor(
[[ 1.0214412e-02  1.0329938e-01 -1.4048357e+00  3.4954715e-01
  -7.6172426e-02]
 [ 2.7158629e-14  4.0548715e-01  6.4203761e-07  1.2941241e+07
  -1.2311462e-10]
 [-9.2751140e-11 -0.0000000e+00  3.8837784e-17  2.8962132e-28
  -0.0000000e+00]
 [-6.7373844e-30  1.4074189e-06  1.1272158e-09 -0.0000000e+00
   2.2677509e-01]
 [ 8.0249138e+01 -5.8582546e-29 -0.0000000e+00  2.6734177e+01
  -4.0605034e+01]], shape=(5, 5), dtype=float32)


## E. Menampilkan nilai maksimal dan minimal dari variable random_tensor

In [158]:
# Membuat variable baru untuk mengindikasikan max dan min
tf_max = tf.argmax(random_tensor, axis=0)
tf_min = tf.argmin(random_tensor, axis=1)

# Menampilkan Nilai Maksimum kolom random_tensor
print("Nilai maksimum (kolom) :", tf_max.numpy())
 
# Menampilkan Nilai Minimum baris random_tensor
print("Nilai minimum (baris) :", tf_min.numpy())

Nilai maksimum (kolom) : [4 1 3 1 3]
Nilai minimum (baris) : [2 4 0 0 4]


## F. Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [159]:
concated = tf.concat([random_tensor, prime_tensor], axis=0)
print("Hasil penggabungan variable random_tensor dengan prime_tensor :", concated.shape)

Hasil penggabungan variable random_tensor dengan prime_tensor : (10, 5)


## G. Menampilkan hasil sorting dari kedua variable secara descending

In [160]:
# Sorting variable random_tensor
sortrandom = tf.sort(random_tensor, direction="DESCENDING")
print("Hasil pengurutan variable random_tensor(descending) :", sortrandom.numpy())

# Sorting variable prime_tensor
sortprime = tf.sort(prime_tensor, direction="DESCENDING")
print("\nHasil pengurutan variable prime_tensor(descending) :", sortprime.numpy())

Hasil pengurutan variable random_tensor(descending) : [[ 0.86057067  0.46920854 -0.10106637 -0.79130745 -1.0703483 ]
 [ 2.038057    0.94828707  0.47215232  0.09045956 -0.45528835]
 [ 0.397867    0.22886398 -0.03072531 -0.0629163  -0.47464088]
 [ 0.9798792   0.7958308   0.71336466 -0.28134418 -0.28157505]
 [ 1.0570775   1.034456   -0.3012637  -0.4569331  -1.0373529 ]]

Hasil pengurutan variable prime_tensor(descending) : [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73.  71.  61.  59.  53.]
 [101.  97.  89.  83.  79.]]
